import { Theme } from '../../../../models/design-models';
import { useAppSelector } from '../../../../store/redux';
import Button from '../../buttons/Button';
import Modal from '../Modal';
import ModalHeader from './content/ModalHeader';
import classes from './GeneralModal.module.scss';

interface ModalProps {
    onAction: (patchGenerated: boolean) => void;
    onClose: () => void;
    targetName?: string;
}

const RecurringModalDeleteModal: React.FC<ModalProps> = (props) => {
    const { onClose, onAction, targetName } = props;
    const itemType = useAppSelector((state) => state.recurring.mode).toLowerCase();

    return (
        <Modal onClose={onClose} modalClass={`${classes.modal} ${classes['modal--edit']}`}>
            <ModalHeader title="Edit" onClose={onClose} />
            <p>
                Do you want to edit all existing one-off {itemType}s generated by this recurring{' '}
                {itemType} {targetName && <strong>&quot;{targetName}&quot;</strong>}
                &nbsp;?
            </p>
            <div className={classes.btns}>
                <Button theme={Theme.SECONDARY} onClick={onAction.bind(null, true)}>
                    Yes
                </Button>
                <Button
                    theme={Theme.PRIMARY}
                    onClick={onAction.bind(null, false)}
                    // className={`${classes['btn-cancel']}`}
                >
                    No
                </Button>
            </div>
        </Modal>
    );
};

export default RecurringModalDeleteModal;
