/*
BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:yjo827@aucklanduni.ac.nz
X-WR-TIMEZONE:Pacific/Auckland
BEGIN:VTIMEZONE
TZID:Australia/Sydney
X-LIC-LOCATION:Australia/Sydney
BEGIN:STANDARD
TZOFFSETFROM:+1100
TZOFFSETTO:+1000
TZNAME:AEST
DTSTART:19700405T030000
RRULE:FREQ=YEARLY;BYMONTH=4;BYDAY=1SU
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:+1000
TZOFFSETTO:+1100
TZNAME:AEDT
DTSTART:19701004T020000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=1SU
END:DAYLIGHT
END:VTIMEZONE
*/
export const VACL_GOOGLE_CALENDAR_BEGINNING: string = [
    'BEGIN:VCALENDAR',
    'PRODID:-//Task Manager Inc//Task Manager Calendar 70.9054//EN',
    'VERSION:2.0',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    'X-WR-CALNAME:yjo827@aucklanduni.ac.nz',
    'X-WR-TIMEZONE:Pacific/Auckland',
    'BEGIN:VTIMEZONE',
    'TZID:Australia/Sydney',
    'X-LIC-LOCATION:Australia/Sydney',
    'BEGIN:STANDARD',
    'TZOFFSETFROM:+1100',
    'TZOFFSETTO:+1000',
    'TZNAME:AEST',
    'DTSTART:19700405T030000',
    'RRULE:FREQ=YEARLY;BYMONTH=4;BYDAY=1SU',
    'END:STANDARD',
    'BEGIN:DAYLIGHT',
    'TZOFFSETFROM:+1000',
    'TZOFFSETTO:+1100',
    'TZNAME:AEDT',
    'DTSTART:19701004T020000',
    'RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=1SU',
    'END:DAYLIGHT',
    'END:VTIMEZONE\n',
].join('\n');

export const VCAL_AUCKLAND_BEGINNING =
    'BEGIN:VCALENDAR\n' +
    'VERSION:2.0\n' +
    'PRODID:-//The University of Auckland//UoACal 2.0//EN\n' +
    'METHOD:PUBLISH\n' +
    'X-WR-CALNAME:UoA Timetable\n' +
    'X-WR-CALDESC:UoA Timetable obtained from uoacal.auckland.ac.nz\n' +
    'X-WR-TIMEZONE:Pacific/Auckland\n' +
    'X-PUBLISHED-TTL:PT12H\n' +
    'BEGIN:VTIMEZONE\n' +
    'TZID:Pacific/Auckland\n' +
    'X-LIC-LOCATION:Pacific/Auckland\n' +
    'BEGIN:STANDARD\n' +
    'DTSTART:20230402T030000\n' +
    'TZOFFSETFROM:+1300\n' +
    'TZOFFSETTO:+1200\n' +
    'TZNAME:NZST\n' +
    'END:STANDARD\n' +
    'BEGIN:DAYLIGHT\n' +
    'DTSTART:20220925T020000\n' +
    'TZOFFSETFROM:+1200\n' +
    'TZOFFSETTO:+1300\n' +
    'TZNAME:NZDT\n' +
    'END:DAYLIGHT\n' +
    'END:VTIMEZONE\n';

export const VCAL_ENDING = 'END:VCALENDAR';
